---
spring:
    application:
        name: basicspiring
    profiles: 
        active: test
management:
    endpoints:
        web:
            exposure:
                include: 
                    -   env
                    -   health
                    -   info
