---
spring:
    application:
        name: basicspiring
    profiles: 
        active: test
test: "greetings from DevOps SpringBoot!"
management:
    endpoints:
        web:
            exposure:
                include: 
                    -   env
                    -   health
                    -   info
